version: '3.8'
services:
  canopus-dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canopus
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5

  # canopus-api:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - canopus-dev-db
  #   ports:
  #     - '4000:4000'

  #   env_file:
  #     - .env
  #   environment:
  #     NODE_ENV: production
  #   command: ['npm', 'run', 'start:prod']

volumes:
  pgdata:
