version: '3.8'
services:
  canopus-dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canopus
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  canopus-api:
    build:
      context: .
      target: production
    restart: always
    depends_on:
      canopus-dev-db:
        condition: service_healthy
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://postgres:password@canopus-dev-db:5432/canopus?schema=public'
    command: sh -c "pnpm run prisma:migrate:deploy && pnpm run start:prod"

volumes:
  pgdata:
